name: cancel-workflow
on: workflow_dispatch
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
          run: echo "Job 1"

  job2:
    runs-on: ubuntu-latest
    if: success() # This job will only run if job1 succeeds
    steps:
      - name: Step 2
        run: echo "Job 2"

  job3:
    runs-on: ubuntu-latest
    if: success() # This job will only run if job1 succeeds
    steps:
      - name: Step 3
        run: echo "Job 3"
