name: cancel-workflow
on: workflow_dispatch
jobs:
  test-job1:
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
          run: exit 1

  test-job2:
    runs-on: ubuntu-latest
    needs: test-job1
    if: success() # This job will only run if job1 succeeds
    steps:
      - name: Step 2
        run: echo "Job 2"
        
  test-job3:
    runs-on: ubuntu-latest
    needs: test-job1
    if: success() # This job will only run if job1 succeeds
    steps:
      - name: Step 3
        run: echo "Job 3"   

  cancel-workflow:
    runs-on: ubuntu-latest
    if: success() # This job will only run if job1 succeeds
    steps:
      - name: Step 3
        run: echo "Job 3"
